//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/XMLSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("NKX", Namespace = "http://tempuri.org/XMLSchema.xsd", IsNullable = false)]
public partial class NKEmpowerTrackpointExtension_t {
    private double strokeRateField;

    private bool strokeRateFieldSpecified;

    private double speedField;

    private bool speedFieldSpecified;

    private double wattsField;

    private bool wattsFieldSpecified;

    private int catchAngleField;

    private bool catchAngleFieldSpecified;

    private int finishAngleField;

    private bool finishAngleFieldSpecified;

    private int maxForceAngleField;

    private bool maxForceAngleFieldSpecified;

    private double avgHandleForceField;

    private bool avgHandleForceFieldSpecified;

    private double maxHandleForceField;

    private bool maxHandleForceFieldSpecified;

    private int slipAngleField;

    private bool slipAngleFieldSpecified;

    private int washAngleField;

    private bool washAngleFieldSpecified;

    private double workPerStrokeField;

    private bool workPerStrokeFieldSpecified;

    /// <remarks/>
    public double StrokeRate
    {
        get
        {
            return this.strokeRateField;
        }
        set
        {
            this.strokeRateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StrokeRateSpecified
    {
        get
        {
            return this.strokeRateFieldSpecified;
        }
        set
        {
            this.strokeRateFieldSpecified = value;
        }
    }

    /// <remarks/>
    public double Speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SpeedSpecified
    {
        get
        {
            return this.speedFieldSpecified;
        }
        set
        {
            this.speedFieldSpecified = value;
        }
    }

    /// <remarks/>
    public double Watts {
        get {
            return this.wattsField;
        }
        set {
            this.wattsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WattsSpecified {
        get {
            return this.wattsFieldSpecified;
        }
        set {
            this.wattsFieldSpecified = value;
        }
    }

    /// <remarks/>
    public int CatchAngle {
        get {
            return this.catchAngleField;
        }
        set {
            this.catchAngleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CatchAngleSpecified {
        get {
            return this.catchAngleFieldSpecified;
        }
        set {
            this.catchAngleFieldSpecified = value;
        }
    }

    /// <remarks/>
    public int FinishAngle {
        get {
            return this.finishAngleField;
        }
        set {
            this.finishAngleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FinishAngleSpecified {
        get {
            return this.finishAngleFieldSpecified;
        }
        set {
            this.finishAngleFieldSpecified = value;
        }
    }

    /// <remarks/>
    public int MaxForceAngle {
        get {
            return this.maxForceAngleField;
        }
        set {
            this.maxForceAngleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxForceAngleSpecified {
        get {
            return this.maxForceAngleFieldSpecified;
        }
        set {
            this.maxForceAngleFieldSpecified = value;
        }
    }

    /// <remarks/>
    public double AvgHandleForce {
        get {
            return this.avgHandleForceField;
        }
        set {
            this.avgHandleForceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AvgHandleForceSpecified {
        get {
            return this.avgHandleForceFieldSpecified;
        }
        set {
            this.avgHandleForceFieldSpecified = value;
        }
    }

    /// <remarks/>
    public double MaxHandleForce {
        get {
            return this.maxHandleForceField;
        }
        set {
            this.maxHandleForceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxHandleForceSpecified {
        get {
            return this.maxHandleForceFieldSpecified;
        }
        set {
            this.maxHandleForceFieldSpecified = value;
        }
    }

    /// <remarks/>
    public int SlipAngle {
        get {
            return this.slipAngleField;
        }
        set {
            this.slipAngleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SlipAngleSpecified {
        get {
            return this.slipAngleFieldSpecified;
        }
        set {
            this.slipAngleFieldSpecified = value;
        }
    }

    /// <remarks/>
    public int WashAngle {
        get {
            return this.washAngleField;
        }
        set {
            this.washAngleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WashAngleSpecified {
        get {
            return this.washAngleFieldSpecified;
        }
        set {
            this.washAngleFieldSpecified = value;
        }
    }

    /// <remarks/>
    public double WorkPerStroke {
        get {
            return this.workPerStrokeField;
        }
        set {
            this.workPerStrokeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WorkPerStrokeSpecified {
        get {
            return this.workPerStrokeFieldSpecified;
        }
        set {
            this.workPerStrokeFieldSpecified = value;
        }
    }

    public NKEmpowerTrackpointExtension_t() { }

    public NKEmpowerTrackpointExtension_t(double speed)
    {
        Speed = speed;
        SpeedSpecified = true;
    }

    public NKEmpowerTrackpointExtension_t(double speed, double power, int catchAngle, int finishAngle, int maxForceAngle, double avgHandleForce, double maxHandleForce,
        int slipAngle, int washAngle, double workPerStroke) : this(speed)
    {
        Watts = power;
        WattsSpecified = true;
        CatchAngle = catchAngle;
        CatchAngleSpecified = true;
        FinishAngle = finishAngle;
        FinishAngleSpecified = true;
        MaxForceAngle = maxForceAngle;
        MaxForceAngleSpecified = true;
        AvgHandleForce = avgHandleForce;
        AvgHandleForceSpecified = true;
        MaxHandleForce = maxHandleForce;
        MaxHandleForceSpecified = true;
        SlipAngle = slipAngle;
        SlipAngleSpecified = true;
        WashAngle = washAngle;
        WashAngleSpecified = true;
        WorkPerStroke = workPerStroke;
        WorkPerStrokeSpecified = true;
    }
}
